### ISSUE TITLE
[PRoot]: carry some patches

### ISSUE THREAD

**Issue by jessfraz** [genuinetools/img#15]
see: https://github.com/AkihiroSuda/runrootless

and xattrs for rootless

**Comment by AkihiroSuda** [comment]
PRoot is currently slow because seccomp acceleration has been broken with recent kernels.
(Tracked in https://github.com/proot-me/PRoot/pull/130 but seems still broken now)

So I'd suggest using rootless runc with SUID `newuidmap` tools.
(It requires my several PRs. review is welcome :penguin: https://github.com/opencontainers/runc/pulls?q=is%3Apr+is%3Aopen+label%3Arootless-containers)

At least, PRoot should be only enabled for apt/apk/yum commands.

**Comment by AkihiroSuda** [comment]
cc @cyphar

**Comment by AkihiroSuda** [comment]
FYI here is some benchmark result of PRoot https://github.com/AkihiroSuda/runrootless/issues/14

**Comment by jessfraz** [comment]
oh cool thanks so much for the info!
